# use case: organization has mandatory format of firstname.lastname for user UPN in AD
# this contains 2 separate scripts. first to list all users where username format does not follow firstname.lastname, and then second command to update/correct


$users = Import-CSV -path "C:\Powershell\UserAlias\Test.csv" # defines users from user CSV. optionally could pipe using get-aduser
$CompleteReport=@() # stores empty array in CompleteReport variable
foreach ($user in $users) { # iterates through each user
    $firstname = $user.first 
    $lastname = $user.last
    $fullusername =  ("{0}.{1}@domain.com" -f $firstname,$lastname) # defines full user name combining variables first and last name
    $aduser = Get-ADUser -filter * | where UserPrincipalName -notlike "$fullusername" # stores all users generated by get-aduser where their UPN does not match fullusername defined above
    $CompleteReport = $CompleteReport+$aduser # adds each aduser to array CompleteReport
}
$CompleteReport | Export-CSV "C:\Powershell\UserAlias\correctalias.csv -NoTypeInformation
#exports to csv


$users = Import-CSV -path "C:\Powershell\UserAlias\AntisUsersNeedToBeChanged.csv"
foreach ($user in $users) {
    $firstname = $user.first
    $lastname = $user.last
    $newAlias = ("{0}.{1}@antisroofing.com" -f $firstname,$lastname)
    set-aduser $firstname -add @{ProxyAddresses="smtp:$newAlias"}
}
